<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Site1.Master" AutoEventWireup="true" CodeBehind="ItemType.aspx.cs" Inherits="TestUser.Views.WebForm3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
        <h3>Категории</h3>
        <hr />
        <asp:GridView 
            ID="GridView1" 
            runat="server" 
            AutoGenerateColumns="False"
            DataKeyNames="itemTypeId" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            CellSpacing="2" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="Номер категории">
                    <ItemTemplate>
                        <asp:Label ID="lbItemTypeId" runat="server" Text='<%# Bind("itemTypeId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Категория">
                    <EditItemTemplate>
                        <asp:TextBox ID="tbItemTypeName" runat="server" Text='<%# Bind("itemTypeName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbItemTypeName" runat="server" Text='<%# Bind("itemTypeName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <h3>Добавить</h3>
        <hr />
        <asp:TextBox ID="tbNewItemType" runat="server"></asp:TextBox>
        <asp:Button ID="btnCreate" runat="server" Text="Добавить" OnClick="btnCreate_Click" />
    </div>
</asp:Content>
