<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Site1.Master" AutoEventWireup="true" CodeBehind="Position.aspx.cs" Inherits="TestUser.Views.WebForm2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Профиль</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="row">
        <h3>Должности</h3>
        <hr />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
            DataKeyNames="positionId" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellSpacing="2" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
            <Columns>
                <asp:TemplateField HeaderText="Номер должности">
                    <ItemTemplate>
                        <asp:Label ID="lbPosId" runat="server" Text='<%# Bind("positionId") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Должность">
                    <EditItemTemplate>
                        <asp:TextBox ID="tbPosName" runat="server" Text='<%# Bind("positionName") %>'></asp:TextBox>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="lbPosName" runat="server" Text='<%# Bind("positionName") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <h3>Добавить</h3>
        <hr />
        <asp:TextBox ID="tbNewPos" runat="server"></asp:TextBox>
        <asp:Button ID="btnCreate" runat="server" Text="Добавить"  OnClick="btnCreate_Click"/>
    </div>
</asp:Content>
